basePath: /
definitions:
  api.userInput:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.JSONResult:
    properties:
      data: {}
      message:
        example: description of the response from the server
        type: string
    type: object
host: https://letsgochat.herokuapp.com
info:
  contact: {}
  description: Online chat in golang
  title: Lets go chat
  version: "1.0"
paths:
  /chat:
    get:
      consumes:
      - application/json
      description: Endpoint to start real time chat
      parameters:
      - description: token
        in: query
        name: string
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful server response
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Connecting to chat
      tags:
      - Chat
  /user:
    post:
      consumes:
      - application/json
      description: Registration a new user in the system
      parameters:
      - description: Please enter your username and password to register
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.userInput'
      produces:
      - application/json
      responses:
        "200":
          description: Successful server response
          schema:
            allOf:
            - $ref: '#/definitions/models.JSONResult'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Invalid input request
          schema:
            allOf:
            - $ref: '#/definitions/models.JSONResult'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/models.JSONResult'
            - properties:
                data:
                  type: string
              type: object
      summary: Sign up
      tags:
      - Users
  /user/active:
    get:
      consumes:
      - application/json
      description: Number of active users in a chat
      produces:
      - application/json
      responses:
        "200":
          description: Returns all active users in the chat
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Active users
      tags:
      - Users
  /user/login:
    post:
      consumes:
      - application/json
      description: User account login
      parameters:
      - description: Please enter your username and password to login
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.userInput'
      produces:
      - application/json
      responses:
        "200":
          description: Successful server response
          schema:
            allOf:
            - $ref: '#/definitions/models.JSONResult'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Invalid input request
          schema:
            allOf:
            - $ref: '#/definitions/models.JSONResult'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/models.JSONResult'
            - properties:
                data:
                  type: string
              type: object
      summary: Sign in
      tags:
      - Users
swagger: "2.0"
